/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene el perfil privado de la persona autenticada */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Perfil */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /** Crea o actualiza el perfil */
        put: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match"?: components["parameters"]["IfMatch"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileInput"];
                };
            };
            responses: {
                /** @description Perfil actualizado */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                412: components["responses"]["PreconditionFailed"];
                428: components["responses"]["PreconditionRequired"];
            };
        };
        post?: never;
        /** Solicita la supresión de la cuenta */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Solicitud aceptada */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/push-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualiza preferencias de notificaciones */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PushSettings"];
                };
            };
            responses: {
                /** @description Preferencias actualizadas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PushSettings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista eventos propios */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: "published" | "cancelled" | "closed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eventos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publica un evento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventInput"];
                };
            };
            responses: {
                /** @description Evento publicado */
                201: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetail"];
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Descubre eventos futuros por radio */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventSearch"];
                };
            };
            responses: {
                /** @description Eventos visibles sin ubicación exacta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventSearchPage"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Obtiene un evento visible */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Evento */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edita un evento propio */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match"?: components["parameters"]["IfMatch"];
                };
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventPatch"];
                };
            };
            responses: {
                /** @description Evento actualizado */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventDetail"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                412: components["responses"]["PreconditionFailed"];
                428: components["responses"]["PreconditionRequired"];
            };
        };
        trace?: never;
    };
    "/events/{eventId}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela un evento propio antes de su inicio */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Evento cancelado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Lista participantes de un evento propio (confirmados o pendientes) */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: "confirmed" | "pending";
                };
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Participantes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ParticipantPage"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Crea una participación o solicitud */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        invitationCode?: string;
                    };
                };
            };
            responses: {
                /** @description Participación creada */
                201: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Participation"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Abandona una participación confirmada */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Participación abandonada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/participations/{participationId}": {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                eventId: components["parameters"]["EventId"];
                participationId: components["parameters"]["ParticipationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aprueba o rechaza una solicitud pendiente */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match"?: components["parameters"]["IfMatch"];
                };
                path: {
                    eventId: components["parameters"]["EventId"];
                    participationId: components["parameters"]["ParticipationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "confirmed" | "rejected";
                    };
                };
            };
            responses: {
                /** @description Participación resuelta */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Participation"];
                    };
                };
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                412: components["responses"]["PreconditionFailed"];
                428: components["responses"]["PreconditionRequired"];
            };
        };
        trace?: never;
    };
    "/events/{eventId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea una invitación privada */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        expiresAt?: string;
                        maxUses?: number;
                    };
                };
            };
            responses: {
                /** @description Invitación; el código solo se devuelve al creador */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invitation"];
                    };
                };
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
                invitationId: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoca una invitación privada */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                    invitationId: components["parameters"]["InvitationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invitación revocada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista bloqueos creados por la persona autenticada */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bloqueos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CursorPage"];
                    };
                };
            };
        };
        put?: never;
        /** Crea un bloqueo recíproco lógico */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        blockedUserId: components["schemas"]["Uuid"];
                    };
                };
            };
            responses: {
                /** @description Bloqueo creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{blockedUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockedUserId: components["parameters"]["BlockedUserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Elimina un bloqueo propio */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    blockedUserId: components["parameters"]["BlockedUserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bloqueo eliminado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reporta un usuario o evento visible */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportInput"];
                };
            };
            responses: {
                /** @description Reporte creado */
                201: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista reportes para moderación */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "archived" | "resolved";
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reportes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportPage"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        /** Obtiene un reporte para moderación */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reporte */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminReport"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resuelve o archiva un reporte */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match"?: components["parameters"]["IfMatch"];
                };
                path: {
                    reportId: components["parameters"]["ReportId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ModerationDecision"];
                };
            };
            responses: {
                /** @description Reporte actualizado */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminReport"];
                    };
                };
                403: components["responses"]["Forbidden"];
                412: components["responses"]["PreconditionFailed"];
                428: components["responses"]["PreconditionRequired"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        GeoPoint: {
            /** @enum {string} */
            type: "Point";
            coordinates: number[];
        };
        PublicProfile: {
            id: components["schemas"]["Uuid"];
            alias: string;
        };
        ManualSearchArea: {
            longitude: number;
            latitude: number;
            label: string;
        };
        ProfileInput: {
            alias: string;
            /** @enum {boolean} */
            adultConfirmed: true;
            termsVersion: string;
            privacyVersion: string;
            guidelinesVersion: string;
            /** @description Ausente conserva la preferencia actual; null la elimina. */
            manualSearchArea?: components["schemas"]["ManualSearchArea"] | null;
        };
        Profile: components["schemas"]["PublicProfile"] & {
            /** @enum {string} */
            status: "active" | "suspended" | "deletion_requested";
            emailVerified: boolean;
            agreementsAccepted: boolean;
            termsVersion: string;
            privacyVersion: string;
            guidelinesVersion: string;
            /** Format: date-time */
            termsAcceptedAt: string;
            /** Format: date-time */
            privacyAcceptedAt: string;
            /** Format: date-time */
            guidelinesAcceptedAt: string;
            manualSearchArea?: components["schemas"]["ManualSearchArea"];
            /** @enum {string} */
            role: "user" | "admin";
        };
        EventInput: {
            title: string;
            description: string;
            notes?: string;
            /** @enum {string} */
            category: "sportWellbeing" | "cultureLeisure" | "learning" | "communityVolunteering" | "pets" | "networking";
            /** Format: date-time */
            startsAt: string;
            durationMinutes: number;
            exactLocation: components["schemas"]["GeoPoint"];
            /** @enum {string} */
            accessMode: "direct" | "approval" | "privateInvitation";
            capacity?: number | null;
        };
        EventPatch: {
            title?: string;
            description?: string;
            notes?: string;
            /** @enum {string} */
            category?: "sportWellbeing" | "cultureLeisure" | "learning" | "communityVolunteering" | "pets" | "networking";
            /** Format: date-time */
            startsAt?: string;
            durationMinutes?: number;
            exactLocation?: components["schemas"]["GeoPoint"];
            /** @enum {string} */
            accessMode?: "direct" | "approval" | "privateInvitation";
            capacity?: number | null;
        };
        EventSearch: {
            origin: components["schemas"]["GeoPoint"];
            radiusMeters: number;
            categories?: string[];
            cursor?: string | null;
            /** @default 20 */
            limit: number;
        };
        EventDiscovery: {
            id: components["schemas"]["Uuid"];
            title: string;
            description: string;
            category: string;
            /** Format: date-time */
            startsAt: string;
            durationMinutes: number;
            accessMode: string;
            capacity?: number | null;
            confirmedCount: number;
            /** @enum {string} */
            availability: "available" | "full";
            approximateArea: string;
            distanceMeters?: number;
            creator: components["schemas"]["PublicProfile"];
        };
        EventDetail: components["schemas"]["EventDiscovery"] & {
            notes?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            myParticipation?: "pending" | "confirmed" | "rejected" | "abandoned";
            exactLocation?: components["schemas"]["GeoPoint"];
            confirmedParticipants?: components["schemas"]["PublicProfile"][];
        };
        Participation: {
            id: components["schemas"]["Uuid"];
            eventId: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "pending" | "confirmed" | "rejected" | "abandoned";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            resolvedAt?: string | null;
        };
        Invitation: {
            id: components["schemas"]["Uuid"];
            code: string;
            /** Format: date-time */
            expiresAt?: string | null;
            maxUses?: number | null;
        };
        PushSettings: {
            enabled: boolean;
            expoPushToken?: string | null;
            preferences?: {
                [key: string]: boolean;
            };
        };
        ReportInput: {
            /** @enum {string} */
            targetType: "user" | "event";
            targetId: components["schemas"]["Uuid"];
            /** @enum {string} */
            reason: "inappropriateContent" | "abusiveBehavior" | "fraudulentEvent" | "misleadingLocation" | "other";
            description?: string;
        };
        ModerationDecision: {
            /** @enum {string} */
            status: "archived" | "resolved";
            /** @enum {string} */
            action: "none" | "hideEvent" | "warnUser" | "suspendUser";
            note?: string;
        };
        ReportCreated: {
            id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "pending";
            /** Format: date-time */
            createdAt: string;
        };
        AdminReport: {
            id: components["schemas"]["Uuid"];
            reporterId: components["schemas"]["Uuid"];
            /** @enum {string} */
            targetType: "user" | "event";
            targetId: components["schemas"]["Uuid"];
            reason: string;
            description?: string | null;
            /** @enum {string} */
            status: "pending" | "archived" | "resolved";
            action?: string | null;
            note?: string | null;
            decidedBy?: components["schemas"]["Uuid"];
            /** Format: date-time */
            decidedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReportPage: {
            items: components["schemas"]["AdminReport"][];
            page: {
                nextCursor: string | null;
            };
        };
        CursorPage: {
            items: Record<string, never>[];
            page: {
                nextCursor: string | null;
            };
        };
        EventPage: components["schemas"]["CursorPage"];
        EventSearchPage: components["schemas"]["CursorPage"] & {
            suggestedRadiusMeters?: number;
        };
        ParticipantPage: components["schemas"]["CursorPage"];
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            detail?: string;
            fields?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description JWT ausente, inválido o expirado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Operación no permitida */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso inexistente u oculto */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Regla de negocio incumplida */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Solicitud inválida */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description ETag desactualizado */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Falta If-Match */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        EventId: components["schemas"]["Uuid"];
        ParticipationId: components["schemas"]["Uuid"];
        InvitationId: components["schemas"]["Uuid"];
        ReportId: components["schemas"]["Uuid"];
        BlockedUserId: components["schemas"]["Uuid"];
        Cursor: string;
        Limit: number;
        IfMatch: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Versión opaca del recurso */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
